### ISSUE TITLE
incorrect rotation of legL in all charactors

### ISSUE THREAD

**Issue by AnAnonymousAlt** [36base/girlsfrontline-resources#55]
Hello. I'm a fan of GF and want to do some doujin stuff. 
Thank you for this resource, that's a great project. I appreciate.

Now, I'm using esoteric spine pro to load (with 2.1.27) and modify (with newest version) spines. However, every spine has incorrect rotation happenned on legL1 & legL2 in most move animation (ex. move & die), not in the standing animation (ex. wait & victory). And there's no problem with the model.
![out2](https://user-images.githubusercontent.com/31899704/65000094-56010400-d8b8-11e9-9664-97a8dcd8da57.gif) (standing correctly)
![out](https://user-images.githubusercontent.com/31899704/64999886-682e7280-d8b7-11e9-867a-f671a82c5f4b.gif)
(running incorrectly)

I can fixed it manually of course. But it's too painful to do it on all charactors. 
Do you have any idea about this? Thank you.

**Comment by DigetArk** [comment]
Girls' Frontline's SD is made based on 2.1.27, and it use flipX and flipY function. But, This function has changed into X-position and Y-position since the recent version of Spine(maybe from 3.* version), so it is incompatible, so either you need to extract the gif from 2.1.27 version or revise it. I am not sure if this will help or not, but I wrote down a site to see or extract Girls' Frontline SD and I want you to use it. Thank you.
(https://github.com/36base/girlsfrontline-resources/issues/55)

**Comment by DigetArk** [comment]
https://team-imasara.github.io/spine-gif/

**Comment by AnAnonymousAlt** [comment]
Thank you. That's an awesome page to do some doujin stuff. 

Though I bought spine some times ago. So, I gonna stay with spine for my money. 

Actually, I asked this question in spine's official forum. Their answer is to either stay in 2.1.27 or to manually change animations, by changing x to -1 and copy-pasting all rotation angle to new bones in 3.x version of spine( here we have 5 frames for each bizarre leg). I don't know if this helps, just tell you what I got so far. 

Since I'm about to do a unity game with spine animation of GF. And all the info I got about using spine in unity is after 3.x version. So now, I'm trying to do changes to all charactors and save them in 3.x version. Do you need this transfered files?

Thank you for the help and follow up.

**Comment by DigetArk** [comment]
I don't need it at the moment, but if I need it later, I'll contact you via Github. And I'll be looking forward your doujin game.🙆‍♂️ If you have any more questions, please contact me again. Thank you. :D :D

**Comment by DigetArk** [comment]
Another member of the 36 base needs that files... Can you share it through a Google drive or github?

**Comment by AnAnonymousAlt** [comment]
Sure. But I'm super busy this week. I will get in touch with you next weekend.

**Comment by DigetArk** [comment]
Thank you :D

**Comment by AnAnonymousAlt** [comment]
Sorry. I'm afraid that I have zero time to do anything outside my courses. And I merely just start, so only few were done. Hope I can spend more time on this and share it to you guys some time later.

**Comment by DigetArk** [comment]
Don't rush and take your time. Please do it when you have time 😌
